export const RIGHT_LINK: 'RIGHT_LINK' = "RIGHT_LINK"
export const LEFT_LINK: 'LEFT_LINK' = "LEFT_LINK"
export const SLIDER_LG: 'SLIDER_LG' = "SLIDER_LG"
export const SLIDER_SM: 'SLIDER_SM' = 'SLIDER_SM'
export const FACE_TYPE_BACK: 'FACE_TYPE_BACK' = 'FACE_TYPE_BACK'
export const FACE_TYPE_FRONT: 'FACE_TYPE_FRONT' = 'FACE_TYPE_FRONT'
export const BLOCK_TYPE_RIGHT: 'BLOCK_TYPE_RIGHT' = 'BLOCK_TYPE_RIGHT'
export const BLOCK_TYPE_LEFT: 'BLOCK_TYPE_LEFT' = 'BLOCK_TYPE_LEFT'
